### ISSUE TITLE
Sample project returns HTTP 403 out-of-the-box.

### ISSUE THREAD

**Issue by PhonicUK** [joongonn/mHttp#1]
Steps to reproduce:

 * Clone the repository as-is
 * Open up the solution in VS 2015
 * Run the sample project
 * Browse to http://localhost:8080/
 * HTTP 403 happens.

**Comment by PhonicUK** [comment]
Caused by not normalizing directory path separators when checking that the requested file is in an allowed subdirectory. https://github.com/joongonn/mHttp/blob/master/mHttp/Http/Handlers/StaticFileHandler.cs#L86

**Comment by joongonn** [comment]
Thanks adding an `Exists` guard makes sense.

Btw, the original `AppDomain.CurrentDomain.BaseDirectory` prefix (which assumed one would place static assets in the same executables folder) was added to avoid the second case below.

**Case 1**. Run the program in the context of the release (i.e. deployment drop) directory:
```
joongonn@joongonn-Gene:~/github/mHttp/mHttp.Sample/bin/Release$ mono ./mHttp.Sample.exe 
2016-07-20T17:45:25.276Z  INFO [HttpBackend(0.0.0.0:8080)@1Hz#3] HttpBackend(0.0.0.0:8080)@1Hz with 1 jobs started
```

**Case 2**. Let's run the program from another working directory eg. `/etc/init.d/`
```
joongonn@joongonn-Gene:~/github/mHttp/mHttp.Sample/bin/Release$ cd /etc/init.d/
```
then,
```
joongonn@joongonn-Gene:/etc/init.d$ mono /home/joongonn/github/mHttp/mHttp.Sample/bin/Release/mHttp.Sample.exe 

Unhandled Exception:
System.IO.DirectoryNotFoundException: The specified directory /etc/init.d/web could not be found.
```

**Comment by PhonicUK** [comment]
Surely that'd be up to the application to decide though rather than the server library itself. My web application may well want to serve out of somewhere that's not in its current working directory.

**Comment by joongonn** [comment]
Agreed, given that the library's signature name reads `Route.ServeDirectory`.

Mental note to self - it'll be on the library user('s code) for now if the "rooted" folder behavior is desired ie.
```
var routeTable = new RouteTable(
    Route.ServeDirectory("/web/*", Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "web"));
    ....
);
```
