### ISSUE TITLE
No licence specified.

### ISSUE THREAD

**Issue by PhonicUK** [joongonn/mHttp#3]
What licence is this library under?

**Comment by joongonn** [comment]
I'll go over http://choosealicense.com/ and pick one in a bit ;)

**Comment by PhonicUK** [comment]
I'd like to recommend the MIT licence. Nice and flexible and compatible with most usage scenarios.

**Comment by joongonn** [comment]
Going with permissive MIT to encourage more interests & users to drive continued development of this little project.

**Comment by PhonicUK** [comment]
Thanks :) You can expect more than a few contributions from me. I've recently switched to this after previously using Griffin.Framework for some software I ship.

**Comment by joongonn** [comment]
Cool, user #1. Let's see how far this takes you!
