### ISSUE TITLE
[Suggestion] Switch from the standard GZipStream in the CLR/Mono libraries to DotNetZip

### ISSUE THREAD

**Issue by PhonicUK** [joongonn/mHttp#4]
The reason for this is that the internal GZipStream implementation in Mono relies on libMonoPosixHelper - this is a problem because mono loads this library dynamically which means it can't be statically linked for use in embedded applications and a different version of this library must be shipped for each new architecture that's supported.

Switching to DotNetZip results in a 1 line code change and uses a fully-managed GZip implementation which can run without adding libMonoPosixHelper as a dependency.

It also has the advantage of providing much better archival performance, and allowing you to tune the compression level used to trade off compression ratio v.s. CPU usage.

**Comment by joongonn** [comment]
I'd like to keep the core (`mHttp.dll`) free of external dependencies; going with the approach in [this commit](https://github.com/joongonn/mHttp/commit/044d8598dc5e82cbf7b45c6220a59694403a11d4) instead for now.

This allows upstream client code to provide a custom gzip implementation (and push the DotNetZip.dll dependency upstream). To illustrate using the sample program's route table:-

```
    System.Func<byte[], byte[]> gzipImpl = m.Utils.Compression.GZip; // Uses default System.IO compression
    var routeTable = new RouteTable(
        Route.ServeDirectory("/*", "./web/", gzipImpl),
        ....
        Route.Get("/metrics").With(Lift.ToJsonHandler(server.GetMetricsReport)
                                       .FilterResponse(Filters.GZip(gzipImpl)))
    );
```

On this note, I had plans to make _Filters_ a more opinionated concern of the library (as with other libraries in the wild), say as a pipeline of Request/Response filter chains inside the `RouteTable`. Currently as one can see, _filtering_ is free form and expressed upstream at the client code level through function chaining/transformation.

**Comment by PhonicUK** [comment]
Works for me!

**Comment by PhonicUK** [comment]
Handy tip, Ionic.Zip has a method that matches the signature: `Ionic.Zlib.GZipStream.CompressBuffer`

You can just drop that in as your `gzipFunc` parameter and it 'Just Works(TM)'
