### ISSUE TITLE
Can't add a route for "/" while also having a route for "/*"

### ISSUE THREAD

**Issue by PhonicUK** [joongonn/mHttp#5]
If you use something like the following as your routes:

    Route.Get("/").With((req) => new FileResponse(new FileInfo("./WebRoot/index.html"))),
    Route.ServeDirectory("/*", "./WebRoot/")

The route for "/" will never fire, and falls through to the directory which then 404s. The "/" route being used so I can specify a default page when the endpoint is visited directly without using a redirect.

If you remove the "/*" route, then  the "/" route works correctly.

**Comment by joongonn** [comment]
Updated matching behaviour of Route("`/*`") to *not* capture Uri("`/`"). I think this was actually the behaviour I had some revisions ago.

Note: Will probably hoist the (default) matching logic out of the `Route` class and make it pluggable (ie. template/strategy pattern) in the future.
