### ISSUE TITLE
[Enhancement] Ability to specify custom headers on Route.ServeDirectory.

### ISSUE THREAD

**Issue by PhonicUK** [joongonn/mHttp#6]
For security reasons I specify `X-FRAME-OPTIONS` = `SAMEORIGIN` on pages served by my application.

While it's easy to add this to a `FileResponse` when you do `Route.Get("blah").With(MyHandler)` there's no way I can see currently of adding this header globally for a given route.

**Comment by joongonn** [comment]
Hmm, it can be done but completely non-obvious to the library user (I'll spend time on documentation when we've more users ;)).

Using sample Program.cs as example again,

**1**. As a library user, create your own filter compose function:
```
    // using RequestHandler = System.Func<IHttpRequest, HttpResponse>;
    
    System.Func<RequestHandler, RequestHandler> applySameOriginFilter = firstHandler => {
        return req => {
            var resp = firstHandler(req);
            resp.Headers["X-FRAME-OPTIONS"] = "SAMEORIGIN";
            return resp;
        };
    };
```
**2**. Get hold of the library's original file serving *handler*:
```
    RequestHandler staticFileHandler = new m.Http.Handlers.StaticFileHandler("/*", "./web/", m.Utils.Compression.GZip).Handle;
```

**3**. Then compose them in the RouteTable:
```
    var routeTable = new RouteTable(
        // Looks like this "Route.ServeDirectory" sugar/abstraction isn't serving us well
        // Route.ServeDirectory("/*", "./web/"),
        Route.Get("/*").With(applySameOriginFilter(staticFileHandler)),
        ......
```

If you're in a hurry perhaps you can go with this style first.

Will meditate on this for a bit longer. Trying to *not* impose an opinion of "filtering" into the library *yet*. Eg. filter handling, as a concern, can be imposed as a libray concern inside either one of/a mix of
* the `HttpBackend`
* the `Router`
* the `RouteTable`

I'm still thinking that filters are just `Func`s chaining/composition, left to the imagination/interpretation of the user, outside the library core.

**Comment by PhonicUK** [comment]
Okie doke, a little fiddly but largely makes sense. It would be nice for it to be tidied up in the way you describe. I do like the composition approach to adding filters and other logic without having to rip things apart too much.

**Comment by joongonn** [comment]
**Quick user story to document issue of filtering request & response.**

Suppose we have this service:
```
var RouteTable = new RouteTable(
  Route.Post("/users").With(userSvc.CreateAccount),          // public endpoint
  Route.Post("/login").With(userSvc.Login),                  // public endpoint
  Route.Get("/users/me/balance").With(userSvc.CheckBalance),
  Route.Put("/users/me/balance").With(userSvc.UpdateBalance)
)
```
Two endpoints needs securing
* `CheckBalance`
*  `UpdateBalance`

By checking that incoming request has a valid `X-AuthToken` header or something.

**Current solution**
Library user define his request authentication filter as a composition
```
// using RequestHandler = System.Func<IHttpRequest, HttpResponse>;

System.Func<RequestHandler, RequestHandler> applyAuthFilter = originalHandler => req => {
    if (IsValid(req.Headers["X-AuthToken"])) {
        return originalHandler(req);
    } else {
        return UnAuthorizedResponse;
    }
};
```
And apply it in the RouteTable
```
var RouteTable = new RouteTable(
  ...,
  ...,
  Route.Get("/users/me/balance").With(applyAuthFilter(userSvc.CheckBalance)),
  Route.Put("/users/me/balance").With(applyAuthFilter(userSvc.UpdateBalance))
)
```

**Comment by joongonn** [comment]
Meanwhile,

[Commit](https://github.com/joongonn/mHttp/commit/b05fe39fb69676a6905e06c2ca2434e7770ce494#diff-fda02586dc3ca30651993ff32b55006f) made to deprecate the `Route.ServeDirectory` helper.

**Previously**
```
Route.ServeDirectory("/*", "./web/")
```

**Now**
```
Route.Get("/*").With(new DirectoryInfo("./web/"))
```

**Comment by joongonn** [comment]
@PhonicUK - I'm going with commit 9063f4e3693c5f7f9d5a9a71129fadf7069f9eea (and fd728c21482567d75de63f47c129954db690394e), taking in the  response filter concern into the core library's `Endpoint` class to solve the original use case you raised.

So by now, if you pull in all my latest changes, we should be able to express it pretty elegantly eg.
```
var routeTable = new RouteTable(
    Route.Get("/*").With(new DirectoryInfo(staticWebContentFolder))
                   .ApplyResponseFilter((req, resp) => {
                       resp.Headers["X-FRAME-OPTIONS"] = "SAMEORIGIN";
                       return resp;
                    }),
    ....
```

Holding off from implementing a more elaborate chain-of-responsibility like request/filter functionality into say, the library's`Router` or `RouteTable` to keep things lean (until the time comes for it).

**Comment by PhonicUK** [comment]
Very nice, much appreciated! It's been very cool watching this project that hadn't had any activity since Jan suddenly spring into life again when it's first heavy user turns up. You should get a patreon account or something similar so I can properly thank you for your efforts.

**Comment by joongonn** [comment]
No problem since so far all we've covered were trivial or already `TODO`s in the sources, just no real users to warrant the continued efforts previously. Thanks for the thought though! May set something up if I don't get real work soon and decide to go back to working on this full time for another stretch (;
