### ISSUE TITLE
Serving large files causes high memory usage and performance issues due to cache and internal copies.

### ISSUE THREAD

**Issue by PhonicUK** [joongonn/mHttp#9]
There's no logic in the cache at the moment to ignore files beyond a certain size, meaning that serving large files holds persistent copies in RAM forever, as well as their gzipped copies (which stalls everything when it tries to compress large files).

In addition, a standard `FileResponse` will load the entire contents of a file into a buffer before serving it, causing a large delay and timeout serving large files.

To serve large files of course you'd hold open a `FileStream` and copy from it to the output stream in chunks until it's done, only loading small (user configurable) portions into RAM at any time (if you're uber-clever, you load the next chunk whilst the previously loaded one is being sent down the wire). This however requires some internal messing since everything takes a `byte[]` currently.

I noticed that there's a `//TODO: streamable` on HttpResponse so I know it's on the radar :) My recommendation would be to always use a generic `Stream` object instead and provide a wrapper/alternate constructor that allows it to still take a `byte[]` by stuffing it in a `MemoryStream`.

**Comment by joongonn** [comment]
Two parts to this discussion;

**1. `StaticFileHandler`**

It's doing too much as a "feature-level", encapsulated blackbox sitting in the library core (`mHttp.dll`).
I'd like (to figure out how) to break it down into chainable/composable "unopinionated parts" which the library user can string together to get his desired file-serving behaviour.

**2. Streamable `HttpResponse`**

Yeap `//TODO: streamable` _responses_ was the next most meaningful thing I wanted to work on actually. Followed by streamable _requests_ (currently fully read-ahead as well beneath the hood).

Your recommendation is elegant and straightforward to implement but we'll lose the current ease of thinking/reasoning with responses (eg. about caching) down at the library layer. Eg. if we have this
```
public class HttpResponse // mostly immutable and free of effects
{
    public Stream Body { get; } // vs byte[] Body
}
```
And with _Stream_ as a non thread-safe abstraction, we cannot mindlessly send the _same_ `HttpResponse` object down _multiple_ requesting clients concurrently (leading to multiple server IO threads writing out the `Body` stream concurrently).

 Immediate idea I've got is to do this instead
```
public class HttpResponse // mostly immutable and free of effects
{
    public Stream GetBody() { /* returns a new stream over underlying resource every time */ }
}
```

Will think about this for a bit more.

**Comment by PhonicUK** [comment]
Indeed there is an interesting problem. It's difficult to make using a stream thread-safe without also making it immutable, but this also doesn't lend itself to the composition approach for things like filters on account of creating lots of copies everywhere.

I think the actual approach would be LINQ-style lazy-evaluation. So each of the layers for things like filters and caches don't actually pull on any data at the point they're created but instead keep references to what they belonged to in the first place and only start moving data around when you actually perform an operation on them.

**Comment by joongonn** [comment]
We might be thinking in somewhat similar lines; to add to my own point on **1. `StaticFileHandler`**, as a library user myself, this is what I'll like to be able to do/express:
```
var cache = new SomeGenericCachingFilter(/* TTL, maxEntries, maxResponseSize, etc */);

var routeTable = new RouteTable(
    Route.Get("/*").With(new FileHandler("./web/").Handle)     // dumb, logic-less FileHandler, hits disk every single time on request
                   .ApplyRequestFilter(cache.FilterRequest)   // ingress: intercept request, checks for last-modified-since, early return cached response if any etc
                   .ApplyResponseFilter(Filters.Gzip)
                   .ApplyResponseFilter(cache.FilterResponse) // egress: update cache with 'new' (gzipped, file) response coming from downstream
```

**Comment by PhonicUK** [comment]
You pretty much read my mind.

**Comment by joongonn** [comment]
Documenting some thoughts on **Streamable `HttpResponse`**

**1)** Tweaking `HttpResponse` (as discussed earlier) to
```
    public abstract class HttpResponse
    {
        // HttpStatusCode StatusCode { get; }
        // ... etc ...

        Stream GetBody(); // previously: byte[] Body { get; }
    }

    public class ByteArrayBackedResponse : HttpResponse
    {
        readonly byte[] bytes;

        public ByteArrayBackedResponse(byte[] bytes) {
            this.bytes = bytes;
        }

        public Stream GetBody() => new MemoryStream(bytes);
    }
```

**2)** Will enable us to represent file responses as,
i. For frequently accessed small files 
```
    public class SmallFileResp : ByteArrayBackedResponse
    {
        public SmallFileResp(FileInfo file) : base(File.ReadAllBytes(file.FullName)) { }
    }
```
ii. For huge files
```
    public class BigFileResp : HttpResponse
    {
        readonly FileInfo file;

        public BigFileResp(FileInfo file) {
            this.file = file;
        }

        public Stream GetBody() => File.OpenRead(file.FullName);
    }
```
All good so far.

**But** a `GzipFilter` will probably produce a response like this
```
    public class GZippedResp : HttpResponse
    {
        readonly HttpResponse origResp;

        public GZippedResp(HttpResponse origResp) {
            this.origResp = origResp;;
        }

        public Stream GetBody() => new GZipStream(origResp.GetBody(), CompressionMode.Compress, true);
    }
```

And say when a "Caching(Response)Filter" is applied to return a same `GZippedResp` instance to multiple IO writer threads, it'll actually be running gzip multiple times.

----

Correct semantics but, not the behaviour we actually want (only incur actual gzipping once) hmmm.

**Comment by PhonicUK** [comment]
Write the gzipped responses to disk, modify the file attributes to have the same timestamp as the original, re-compress when the timestamp changes and otherwise just serve those up as normal file responses with the content header for gzipped data.

**Comment by joongonn** [comment]
I've added support for `Stream` backed responses while preserving the original support for `byte[] ` backed responses - which I consider to be the majority/target use case of this library (ie. short restful api service responses). You can get a sense of the internal implementation in [FileResponse.Stream](https://github.com/joongonn/mHttp/blob/master/mHttp/Http/HttpResponse.cs).

If you pull the latest code, you should be getting some compilation errors that shouldn't be too bad to fix. The main one I reckon would be the custom gzip function parts (stock implementation now looks like [this](https://github.com/joongonn/mHttp/blob/master/mHttp/Http/Filters.cs)).

We can't apply filtering over `Stream`s yet eg. returning a gzipped wrapped stream,  mainly because I've not implemented chunked responses yet (to support returning responses with lengths that are not known ahead of time).
